version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_service
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  api:
    image: hainv2501/identity-test-aws:0.1.0
    depends_on:
      - mysql
    ports:
      - "8181:8080"
    env_file: prod.env
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8282:8080"
      - "50000:50000"
    volumes:
      - C:\Volumes\dev\jenkins\jenkins_home:/var/jenkins_home
#    environment:
#      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
#    restart: unless-stopped

volumes:
  mysql:
  jenkins_home:
