version: "3"
networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: identity_service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
