server:
  port: ${PORT}
  servlet:
    context-path: ${CONTEXT_PATH}

spring:
  datasource:
    url: ${MYSQL_URL}
    driverClassName: ${MYSQL_DRIVER_CLASSNAME}
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${JWT_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
